import React from "react";
import {Oswald, Urbanist} from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import ClientProvider from "../components/ClientProvider";

const oswald = Oswald({subsets: ["latin"]});
const urbanist = Urbanist({subsets: ["latin"]});

export const metadata = {
  title: "Online Shoe Store | Stamp Dev",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <ClientProvider>
          <Header />
          {children}
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
